server:
  port: ${_APPLICATION_PORT:8094}

spring:
  application:
    name: Turkcell Kurumsal
  data:
    mongodb:
      database: ${_MONGO_DB:turkcell_poc}
      username: ${_MONGO_UNAME:admin}
      password: ${_MONGO_UPASS:root}
      host: ${_MONGO_HOST:localhost}
      port: ${_MONGO_PORT:27017}
      authentication-database: ${_MONGO_AUTH_DB:admin}

springdoc:
  api-docs:
    path: /api-docs
